test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
cloudinary:
  service: Cloudinary
  secure: true
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) %>
  cloud_name:  <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) %>
